# Generated by Django 6.1 on 2026-08-29 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
        ("recommendations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="useractivity",
            name="search_query",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="useractivity",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_activities",
                to="products.product",
            ),
        ),
    ]
